version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: vicding81/simplesqlinjection-web:latest
    restart: unless-stopped
    volumes:
      - ./app:/app
    ports:
      - "38080:80"
    depends_on:
      - db
  db:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: